implemented limit service
fizikovnet/t1_academy_spring pull request #6
Opened 2024-11-07 10:33 UTC by fizikovnet

2024-11-07 16:48 UTC, Alexandr056 requested changes
на отлично нужны доработки

2024-11-07 16:48 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/controller/LimitController.java
> +    private LimitService limitService;
final

2024-11-07 16:48 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/controller/LimitController.java
> +    public ResponseEntity<Limit> getLimit(@PathVariable Integer clientId) {
ResponseEntity не нужен в контроллере, все равно делаете единственное - OK()

2024-11-07 16:48 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/controller/LimitController.java
> +    public ResponseEntity<String> restoreLimit(@PathVariable Integer clientId, @RequestParam BigDecimal amount) {
ResponseEntity не нужен в контроллере, все равно делаете единственное - OK()

2024-11-07 16:48 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/scheduler/LimitResetScheduler.java
> +            limitRepository.save(limit);
много много запросов, очень не оптимально

2024-11-07 16:48 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/service/LimitService.java
> +    public boolean processPayment(Integer clientId, BigDecimal amount) {
не рекомендую такую реализацию, сейчас у вас единственная причина почему может не пройти процц списания, при сравнении доступного остатка, а когда добавится еще проверка? false - не будет говорить о том, почему не удалось совершить операцию, здесь больше подходит exception для частного случая и его обработка в controller advice

2024-11-07 16:48 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/service/LimitService.java
> +    public boolean processPayment(Integer clientId, BigDecimal amount) {
тогда и в controller не будет ResponseEntity

2024-11-07 16:48 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/service/LimitService.java
> +        resetDailyLimitIfNeeded(limit);
зачем? у вас должно это выполняться по расписанию, вручную для чего?

2024-11-07 16:48 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/service/LimitService.java
> +@AllArgsConstructor
RequiredArgs…

2024-11-07 16:48 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/service/LimitService.java
> +    private LimitRepository limitRepository;
final

2024-11-07 18:06 UTC, fizikovnet commented on limit_service/src/main/java/com/fizikovnet/controller/LimitController.java
> +    private LimitService limitService;
fixed

2024-11-07 18:06 UTC, fizikovnet commented on limit_service/src/main/java/com/fizikovnet/controller/LimitController.java
> +    public ResponseEntity<Limit> getLimit(@PathVariable Integer clientId) {
Ok, fixed

2024-11-07 18:06 UTC, fizikovnet commented on limit_service/src/main/java/com/fizikovnet/controller/LimitController.java
> +    public ResponseEntity<String> restoreLimit(@PathVariable Integer clientId, @RequestParam BigDecimal amount) {
Ok, fixed

2024-11-07 18:08 UTC, fizikovnet commented on limit_service/src/main/java/com/fizikovnet/scheduler/LimitResetScheduler.java
> +            limitRepository.save(limit);
Зарефакторил: добавил в репозиторий кастомный метод для батч обновления всех лимитов одинм запросом, здесь его и вызываю.

2024-11-07 18:09 UTC, fizikovnet commented on limit_service/src/main/java/com/fizikovnet/service/LimitService.java
> +    public boolean processPayment(Integer clientId, BigDecimal amount) {
Да, согласен. Переделал на advice

2024-11-07 18:09 UTC, fizikovnet commented on limit_service/src/main/java/com/fizikovnet/service/LimitService.java
> +@AllArgsConstructor
fixed

2024-11-07 18:09 UTC, fizikovnet commented on limit_service/src/main/java/com/fizikovnet/service/LimitService.java
> +    private LimitRepository limitRepository;
fixed

2024-11-07 18:11 UTC, fizikovnet commented on limit_service/src/main/java/com/fizikovnet/service/LimitService.java
> +        resetDailyLimitIfNeeded(limit);
Ой, это я не до конца задание прочитал, и начал реализовал сначала вручную сброс, потом добавил шедулер, но забыл убрать этот вариант.

2024-11-08 10:56 UTC, Alexandr056 approved these changes
отлично

2024-11-08 10:56 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/controller/LimitController.java
> +    public String processPayment(@PathVariable Integer clientId, @RequestParam BigDecimal amount) {
String возвращать совсем не информативно

2024-11-08 10:56 UTC, Alexandr056 commented on limit_service/src/main/java/com/fizikovnet/controller/LimitController.java
> +    public String restoreLimit(@PathVariable Integer clientId, @RequestParam BigDecimal amount) {
String возвращать совсем не информативно

2024-11-08 10:57 UTC, merged